[package]
name = "dice"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
gloo = "0.3"
gloo-utils = "0.1"
web-sys = "0.3"
